name: Avery Miller
favicon: null
layout_spectrum: 0.24857422104105353
typography_spectrum: 0.44661
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cd3a4d'
    - '#51c5ea'
    - '#000000'
    - '#e7ba5d'
  brandStrength: 0.8196931730490178
  lightness: 0.6875
  saturation: 0.4375
  rhythmicContrast: 0.23843141947872937
purpose: []
