name: Avery Miller
favicon: null
layout_spectrum: 0.24857422104105353
typography_spectrum: 0.44661
title: Avery Miller
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e7ba5d'
    - '#cd3a4d'
    - '#51c5ea'
    - '#3087d4'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
